# Generated by Django 3.1.1 on 2021-03-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
