# Generated by Django 3.1.1 on 2021-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_image',
            field=models.ImageField(default='', upload_to='blog/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_title',
            field=models.CharField(max_length=150),
        ),
    ]
