# Generated by Django 3.1.1 on 2021-03-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210315_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post_title', models.CharField(max_length=150)),
                ('post_image', models.ImageField(upload_to='images/project/products/')),
                ('post_main', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
