# Generated by Django 3.1.1 on 2021-03-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210315_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('profile_image', models.ImageField(upload_to='images/project/reviews/')),
                ('comment', models.TextField(max_length=350)),
                ('date', models.DateField()),
            ],
        ),
    ]
