# Generated by Django 3.1.1 on 2021-03-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_reviews',
            name='comment',
            field=models.TextField(max_length=180),
        ),
    ]
