# Generated by Django 3.1.1 on 2021-03-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210315_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=270)),
                ('facebook_link', models.CharField(max_length=80)),
                ('instagram_link', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('complain_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('brand_name_full', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project_reviews',
            name='comment',
            field=models.TextField(max_length=270),
        ),
    ]
